title: Seungwon Jeong
description: Korea University
site_title: '@portfolio - Seungwon Jeong'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: SeungWon Jeong
blog_url: https://github.com/redlion0929
email: redlion0929@korea.ac.kr
keybase_username: redlion0929


# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 